# theme: jekyll-theme-slate


title                    : "BioChemCoRe 2018"
description              : "Biology and Chemistry Computational Research"
url                      : "https://ctlee.github.io"
baseurl                  : "/BioChemCoRe-2018" # the subpath of your site, e.g. "/blog"
repository               : "ctlee/BioChemCoRe-2018" # GitHub username/repo-name e.g. "mmistakes/minimal-mistakes"
logo_image               : "images/BCCRlogo_highlights.jpg"
company_name             : "BioChemCoRe"


markdown: kramdown
highlighter: rouge

# Markdown Processing
kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false


collections:
  pdbs:
    output: true
    permalink: /:collection/:path/

defaults:
  -
    scope:
      path: "_pdbs"
      type: pdbs
    values:
      layout: pdb
      topnav: topnav
      sidebar: pdbs_sidebar
  -
    scope:
      path: ""
      type: pages
    values:
      layout: page
      topnav: topnav

sidebars:
- pdbs_sidebar

